kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: actor2
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    app: {{ .Release.Name }}-actor2
