name: Docker Java CI

on:
  push:
    branches: 
    - main
    tags:
    - v0.*
    - v1.*
    - v2.*
    - v3.*
    - v4.*
    - v5.*
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: zulu
        java-package: jdk
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: navicore/java-server-example
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
